teleop_twist_joy:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 1.0
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.0
    enable_button: 5
    require_enable_button: true
    use_sim_time: true

    # These are the important lines:
    publish_stamped_twist: true
    publish_stamped_twist_topic: /halleffect_controller/cmd_vel
    publish_stamped_twist_frame_id: base_link  # or your preferred frame