teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 1.0
    axis_angular:
      roll: 0
    scale_angular:
      roll: 1.0
    enable_button: 5
    publish_stamped_twist: true
    require_enable_button: true
    use_sim_time: true
