teleop_twist_joy:
  ros_parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic: halleffect_controller/cmd_vel


      deadman_button: [5]

      axis_mappings:
        twist-linear-x:
          axis: 1
          scale: 1.0
          offset: 0.0
        twist-angular-z:
          axis: 3
          scale: 0.0
          offset: 0.0
