teleop_twist_joy:
  ros__parameters:
    type: topic
    interface_type: geometry_msgs/msg/TwistStamped
    topic_name: halleffect_controller/cmd_vel
    axis_linear:
      x: 1
    scale_linear:
      x: 1.0
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.0
    enable_button: 5
    require_enable_button: true
    use_sim_time: true
